# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97811f83b329de53cadecf92c50c4443cdac2a17bd05272086763fd99ecfd5ca3e34c91ca175b1a81367c44d070fc232f24558ca89be4db8f653a570f4be53f3

test:
  secret_key_base: 515f780c15e8dd202612a595f6016587bea3a489a43771bd3f64ee35ef095aa3da12a3019b699cb8c9f2c4ba2666f03bc41da67c15542eec99352b93f86bb326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
